# Generated by Django 4.2.27 on 2026-05-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backEnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
