# Generated by Django 4.2.27 on 2026-06-10 17:47

import backEnd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backEnd', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=backEnd.models.upload_property_image_path),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=backEnd.models.upload_property_image_path),
        ),
    ]
