# Generated by Django 4.2.27 on 2026-06-12 01:33

import backEnd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backEnd', '0005_alter_property_image_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=backEnd.models.upload_property_image_path),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(max_length=200, upload_to=backEnd.models.upload_property_image_path),
        ),
    ]
