# Generated by Django 4.2.27 on 2026-06-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backEnd', '0006_alter_property_image_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superhost',
            field=models.BooleanField(default=False),
        ),
    ]
