# Generated by Django 4.2.27 on 2026-06-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backEnd', '0009_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
