# Generated by Django 4.2.27 on 2026-07-26 12:59

import backEnd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backEnd', '0011_subscriptionplan_subscription_credittransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=backEnd.models.upload_profile_image_path),
        ),
    ]
