# Generated by Django 4.2.27 on 2026-07-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backEnd', '0012_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
