# Generated by Django 4.2.27 on 2026-09-09 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backEnd', '0014_conversation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='backEnd.conversation'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_request', 'Booking Request'), ('booking_confirmed', 'Booking Confirmed'), ('booking_canceled', 'Booking Canceled'), ('booking_completed', 'Booking Completed'), ('booking_expired', 'Booking Expired'), ('checkin_reminder', 'Check-in Reminder'), ('checkout_reminder', 'Checkout Reminder'), ('booking_paid', 'Booking Paid'), ('new_message', 'New Message')], max_length=30),
        ),
    ]
